bitops:
  # The `bitops.config.yaml` file contains the configuration values for the BitOps core.
  #   - Changing values will require that a new image be built
  #   - Customize your BitOps image by modifying the values found in the `bitops.config.yaml`

  fail_fast: true     # When set, will exit if any warning+ is raised, otherwise only exit on critical error
  run_mode: default   # (Unused for now)
  # LEVELS: [ DEBUG, INFO, WARNING, ERROR, CRITICAL ]
  logging:      
    level: DEBUG              # Sets the logging level
    color:
      enabled: true           # Enables colored logs
    filename: bitops-run      # log filename
    err: bitops.logs          # error logs filename
    path: /var/logs/bitops    # path to log folder
    # Define the secrets to mask
    masks:
      - # regex to search
        # looks for `BITOPS_KUBECONFIG_BASE64={string}`
        search: (.*BITOPS_KUBECONFIG_BASE64.*\=)(.*\n)
        # replace the value part
        replace: '\1*******\n'
      - # regex to search
        # looks for `The namespace kube-system exists`
        search: (.*The namespace )(kube-system)( exists.*)
        #replace kube-system
        replace: '\1*******\3'
      - # looks for `AWS_ACCESS_KEY_ID={string}`
        search: (AWS_ACCESS_KEY_ID=)(\S+)
        replace: \1*******
      - # looks for `AWS_SECRET_ACCESS_KEY={string}`
        search: (AWS_SECRET_ACCESS_KEY=)(\S+)
        replace: \1*******
  default_folder: _default
  plugins:    
    aws:
      source: https://github.com/bitops-plugins/aws
    terraform:
      source: https://github.com/bitops-plugins/terraform
    helm:
      source: https://github.com/bitops-plugins/helm
    kubectl:
      source: https://github.com/bitops-plugins/kubectl
  deployments:
    terraform:
      plugin: terraform
    helm:
      plugin: helm

