bitops:
  project:
    source: local
  
  logging: 
    level: verbose
    file: bitops.logs
    err: bitops.logs
    rotation: 3
    
  plugins:
    plugins_seq:
      - terraform-usage1
      - helm
      - terraform-usage2
    
    tools:
      cloudproviders:
        aws:
          source: https://github.com/bitops-plugins/bitops-aws-plugin

      deployment:
        terraform-usage1:
          source: https://github.com/bitops-plugins/bitops-terraform-plugin
          source_tag: v0.0.1
          version: 0.13.0
          logging:
            level: verbose
          
        
        terraform-usage2:
          source: https://github.com/bitops-plugins/bitops-terraform-plugin
          source_branch: test
          version: 0.13.0
          logging: 
            level: verbose

        helm:
          version: 3.4.1
          namespace: default
          source: https://github.com/bitops-plugins/bitops-helm-plugin
          source_branch: master
          source_tag: v0.0.1
          logging: 
            level: verbose
            file: bitops.helm.logs
            err: bitops.helm.err
        
        kubectl:
          version: 1.13.7
          source: https://github.com/bitops-plugins/bitops-kubectl-plugin
          install_script: install.py
          deploy_script: deploy.py

        ansible:
          version: 2.5
          source: https://github.com/bitops-plugins/bitops-ansible-plugin
