helm:
  type: object
  properties:
    cli:
      type: object
      properties:
        namespace:
          type: string
          parameter: namespace
          export_env: NAMESPACE
          required: true
          dash_type: '--'
        timeout:
          type: string
          parameter: timeout
          export_env: TIMEOUT
          default: "500s"
          dash_type: "---"
        set:
          type: list
          parameter: set
          export_env: HELM_SET_FLAG
        debug:
          type: boolean
          parameter: debug
          export_env: HELM_DEBUG
        atomic:
          type: boolean
          parameter: atomic
          dash_type: "-"
        force:
          type: boolean
          parameter: force
        dry-run:
          type: boolean
          parameter: dry-run
        backend-config:
          type: parameter-list
          parameter: backend-config
    options:
      type: object
      properties:
        skip-deploy:
          type: boolean
          parameter: skip-deploy
          export_env: HELM_SKIP_DEPLOY
        release-name:
          type: string
          export_env: HELM_RELEASE_NAME
        uninstall:
          type: string
          export_env: HELM_UNINSTALL
        kubeconfig:
          type: object
          properties:
            path:
              type: string
              export_env: KUBE_CONFIG_PATH
            fetch:
              type: object
              properties:
                enabled: 
                  type: boolean
                  default: true
                  export_env: FETCH_KUBECONFIG
                cluster-name:
                  type: string
                  export_env: CLUSTER_NAME
        
    plugins:
      type: object
      properties:
        s3:
          type: object
          properties:
            region:
              type: string
              export_env: HELM_PLUGIN_S3_REGION
            bucket:
              type: string
              export_env: HELM_CHARTS_S3_BUCKET
