bitops:
  fail_fast: true
  logging:      
    level: DEBUG              # Sets the logging level
    color:
      enabled: true           # Enables colored logs
  plugins:    
    duplicate-environment: {}
  deployments:
    duplicate-environment:
      plugin: duplicate-environment