name: Build and Publish base image

on:
  workflow_dispatch: 
    inputs:
      bitops_base_tag:
        description: Specifies the tag that will be published
        type: string
        default: base
        required: true
      bump_base_tag:
        description: Bumps the bitops-tag.yaml file, this will trigger the recreation of the official prebuilt plugins images
        type: boolean
        default: false

  push:
    branches: [ main ]
    tags:
      - "*"
    paths-ignore:
      - "docs/**"
      - "prebuilt-config/**"
      - ".github/workflows/build-and-publish-prebuilt.yaml"
      - ".github/workflows/publish-docs.yaml"
      - ".gitignore"
      - "bitops.schema.yaml"
      - "*.md"
      - "mkdocs.yml"

  release:
    types: [ published ]
  
env:
  BASE_TAG: base
  
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
        
    - name: Debugging event name
      run: |
        echo ${{ github.event_name}}

    # ~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~- #
    #                   PUSH                   #
    # ~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~- #  
    - name: Publish Docker Image (Push)
      env:
        REGISTRY_URL: "bitovi/bitops"
        DEFAULT_BRANCH: "plugins"
        DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME}}
        DOCKER_PASS: ${{ secrets.DOCKERHUB_PASSWORD}}
        # On merge to default 'main' branch push current 'dev-base' Docker tag
        IMAGE_TAG: dev-base
      run: |
        echo "running .github/workflows/scripts/docker-publish.sh"
        ./.github/workflows/scripts/docker-publish.sh
      if: github.event_name == 'push'
    

    # ~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~- #
    #           Workflow dispatch              #
    # ~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~- # 
    - name: Publish Docker Image (Workflow dispatch)
      env:
        REGISTRY_URL: "bitovi/bitops"
        DEFAULT_BRANCH: "plugins"
        DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME}}
        DOCKER_PASS: ${{ secrets.DOCKERHUB_PASSWORD}}
        IMAGE_TAG: ${{ github.event.inputs.bitops_base_tag}}
      run: |
        echo "running .github/workflows/scripts/docker-publish.sh"
        ./.github/workflows/scripts/docker-publish.sh
        echo "IMAGE_TAG=${{ github.event.inputs.bitops_base_tag}}" >> $GITHUB_ENV
        echo "IMAGE_BUMP=${{ github.event.release.bump_base_tag }}" >> $GITHUB_ENV
        cat $GITHUB_ENV
      if: github.event_name == 'workflow_dispatch'


    # ~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~- #
    #                Release                   #
    # ~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~- #
    - name: Publish Docker Image (Release)
      env:
        REGISTRY_URL: "bitovi/bitops"
        DEFAULT_BRANCH: "plugins"
        DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME}}
        DOCKER_PASS: ${{ secrets.DOCKERHUB_PASSWORD}}
        # On release push versioned '1.2.3-base' Docker tag
        IMAGE_TAG: ${{ github.event.release.tag_name }}-base
        # On release update additional 'base' Docker tag to refer to the latest stable base
        ADDITIONAL_IMAGE_TAG: base
      run: |
        echo "running .github/workflows/scripts/docker-publish.sh"
        ./.github/workflows/scripts/docker-publish.sh
        echo "IMAGE_TAG=${{ github.event.release.tag_name }}-base" >> $GITHUB_ENV
        echo "IMAGE_BUMP=true" >> $GITHUB_ENV
      if: github.event_name == 'release'


    # ~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~- #
    #         ALL!push: BUMP                   #
    # ~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~- # 
    # Bump the version in `prebuilt-config/bitops-tag
    - name: Bump version tag
      uses: fjogeleit/yaml-update-action@main
      with:
        valueFile: prebuilt-config/bitops-tag.yaml
        propertyPath: 'tags.bitops_base'
        value: ${{ env.BASE_TAG}}
        commitChange: true
        updateFile: true
        branch: main
        masterBranchName: main
      if: env.IMAGE_BUMP == 'true'
